import {
  Award,
  Bed,
  Bell,
  Book,
  Camera,
  Cloud,
  Coffee,
  Crown,
  Gem,
  Grid2X2,
  Heart,
  Home,
  Hotel,
  Layers,
  Layout,
  List,
  Moon,
  Music,
  Package,
  PawPrint,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Sofa,
  Star,
  Sun,
  Tag,
  Truck,
  Utensils,
  User,
  Waves,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const CATEGORY_ICON_OPTIONS: Array<{ key: string; icon: LucideIcon }> = [
  { key: 'Bed', icon: Bed },
  { key: 'Sofa', icon: Sofa },
  { key: 'Layers', icon: Layers },
  { key: 'Hotel', icon: Hotel },
  { key: 'Waves', icon: Waves },
  { key: 'PawPrint', icon: PawPrint },
  { key: 'Cloud', icon: Cloud },
  { key: 'Crown', icon: Crown },
  { key: 'Award', icon: Award },
  { key: 'Wind', icon: Wind },
  { key: 'Star', icon: Star },
  { key: 'Gem', icon: Gem },
  { key: 'Tag', icon: Tag },
  { key: 'Book', icon: Book },
  { key: 'Package', icon: Package },
  { key: 'ShoppingCart', icon: ShoppingCart },
  { key: 'Zap', icon: Zap },
  { key: 'Heart', icon: Heart },
  { key: 'Grid', icon: Grid2X2 },
  { key: 'Grid2X2', icon: Grid2X2 },
  { key: 'List', icon: List },
  { key: 'Layout', icon: Layout },
  { key: 'Utensils', icon: Utensils },
  { key: 'Coffee', icon: Coffee },
  { key: 'Home', icon: Home },
  { key: 'Camera', icon: Camera },
  { key: 'Music', icon: Music },
  { key: 'Truck', icon: Truck },
  { key: 'Bell', icon: Bell },
  { key: 'Moon', icon: Moon },
  { key: 'Sun', icon: Sun },
  { key: 'Search', icon: Search },
  { key: 'Settings', icon: Settings },
  { key: 'User', icon: User },
  { key: 'Shield', icon: Shield },
];

export const CATEGORY_ICON_COMPONENTS = CATEGORY_ICON_OPTIONS.reduce<Record<string, LucideIcon>>((acc, option) => {
  acc[option.key] = option.icon;
  return acc;
}, {});

export function getCategoryIconComponent(iconKey?: string) {
  return iconKey ? (CATEGORY_ICON_COMPONENTS[iconKey] || Grid2X2) : Grid2X2;
}
